### ISSUE TITLE
Can't seem to use with slime because your image's swank is old

### ISSUE THREAD

**Issue by blakemcbride** [madnificent/lisp-webservice-docker#1]

**Comment by madnificent** [comment]
Hi Blake.  You can try `madnificent/lisp-webservice:0.1.0`?

**Comment by madnificent** [comment]
Needs to be fixed in https://github.com/davazp/docker-quicksbcl before it can be fixed here.  Feel free to open an issue there.  Perhaps I'll create a PR.
